{{- if .Values.secrets.app.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hupi.appSecretName" . }}
  labels:
    {{- include "hupi.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUPI_APP_DATABASE_URL: {{ .Values.secrets.app.appDatabaseURL | quote }}
  HUPI_KEK: {{ .Values.secrets.app.kek | quote }}
  {{- range $k, $v := .Values.secrets.app.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
