// Command hupi-correct writes a corrected version of an existing summary
// that supersedes it — see MEMORY_FORMAT.md § Grounding & correction and
// docs/DESIGN_VS_BUILT.md #2. The corrected content is a JSON file you
// write by hand (matching consolidation.ConsolidationOutput's shape), not
// something regenerated by the same LLM that produced the wrong original.
//
// Usage:
//
//	hupi-correct -summary-id sum_2026-09-09_daily_v1 -reason "..." -content correction.json
//
// Where correction.json looks like:
//
//	{
//	  "summary": "corrected prose",
//	  "key_facts": [{"fact": "...", "source_episode_ids": ["..."]}],
//	  "entities_touched": [{"id": "project:hupi", "kind": "project", "name": "HUPI", "attributes": {}}]
//	}
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"hupi/internal/bootstrap"
	"hupi/internal/consolidation"
	"hupi/internal/identity"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "hupi-correct:", err)
		os.Exit(1)
	}
}

func run() error {
	summaryID := flag.String("summary-id", "", "id of the summary to correct, e.g. sum_user:default_2026-09-09_daily_v1")
	reason := flag.String("reason", "", "why this correction is being made (required)")
	contentPath := flag.String("content", "", "path to a JSON file with the corrected content")
	scopeKind := flag.String("scope-kind", identity.ScopeKindPrivate, "private | shared — must match the scope the summary was written in")
	scopeOwner := flag.String("scope-owner", identity.DefaultUserID, "user id (private) or team id (shared)")
	actor := flag.String("actor", defaultActor(), "who's making this correction — recorded on the audit log entry (docs/GAP_CLOSURE_PLAN.md §4.3); defaults to $USER")
	flag.Parse()

	if *summaryID == "" || *reason == "" || *contentPath == "" {
		return fmt.Errorf("usage: hupi-correct -summary-id <id> -reason <text> -content <file.json> [-scope-kind private|shared] [-scope-owner <id>]")
	}

	data, err := os.ReadFile(*contentPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", *contentPath, err)
	}
	var output consolidation.ConsolidationOutput
	if err := json.Unmarshal(data, &output); err != nil {
		return fmt.Errorf("parse %s: %w", *contentPath, err)
	}

	ctx := context.Background()
	deps, err := bootstrap.Load(ctx)
	if err != nil {
		return err
	}
	defer deps.DB.Close()

	runner := consolidation.New(deps.DB, deps.Keys, deps.Registry.Consolidation(), deps.Registry.Grounding(), deps.Registry.Embedding())
	scope := identity.Scope{Kind: *scopeKind, Owner: *scopeOwner}
	if err := runner.Correct(ctx, scope, *summaryID, output, *reason, *actor); err != nil {
		return fmt.Errorf("correct %s: %w", *summaryID, err)
	}

	fmt.Printf("wrote a corrected version superseding %s\n", *summaryID)
	return nil
}

// defaultActor gives -actor a sensible default without forcing every
// invocation to type it — real accountability needs someone to type
// their own name, but a CLI that hangs on a missing flag isn't better.
func defaultActor() string {
	if u := os.Getenv("USER"); u != "" {
		return u
	}
	if u := os.Getenv("LOGNAME"); u != "" {
		return u
	}
	return "unknown"
}
